import type { ReactNode } from 'react'
import { between, intBetween, pick, rngFrom, round, type Rng } from './seed'

/* Seeded cover art, drawn rather than generated by a model.

   The aesthetics the brief asks for — block print, embroidery, folk repeat,
   pressed flower, stamped cloth — are all rule-based and repeating, which is
   the one thing vector geometry does better than a diffusion model. A model
   gives you a soft painting *of* a block print; a compass and a rule give you
   a block print. It is also the only version that is free forever, works with
   no network, and is identical on every regeneration by construction.

   Everything is drawn in the book's own ink — the same relative-colour recipe
   the printed frame and the shelf spines use — so a generated cover is the
   same physical object as every other cover, and dark mode needs no work here
   at all. */

const INK =
  'oklch(from var(--cover-hue, var(--color-image)) var(--book-rule-l) var(--book-rule-c) h)'

/** The art is drawn on a square field and centred in whatever space it gets. */
const SIZE = 120
const MID = SIZE / 2

type Family = (rng: Rng) => ReactNode

interface CoverArtProps {
  seed: number
  className?: string
}

function CoverArt({ seed, className }: CoverArtProps) {
  const rng = rngFrom(seed)
  // Drawn before the family is chosen so that adding a sixth family later
  // does not reshuffle every existing book's art.
  const family = FAMILIES[seed % FAMILIES.length]

  return (
    <svg
      className={className}
      viewBox={`0 0 ${SIZE} ${SIZE}`}
      fill="none"
      stroke={INK}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      focusable="false"
    >
      {family(rng)}
    </svg>
  )
}

/* ---- Pressed specimen ----
   A page from a herbarium: one plant, flattened and mounted. Thin strokes and a
   barely-there wash, because a pressed flower has lost most of its colour.

   The first version had a single anatomy — stem, leaf pairs, one bloom — and
   varied only its numbers. Three covers in twelve came out reading as the same
   plant drawn slightly differently, which is the failure this family is most
   prone to because it is the one that recurs most. A specimen sheet varies by
   species, not by parameter, so this draws five: a single bloom, an umbel, a
   flowering spike, a fern frond and a berried sprig. They differ in silhouette,
   which is what you actually recognise a cover by at thumbnail size. */

interface Pt {
  x: number
  y: number
}

/** Where the stem is, which way it is heading, and which way is sideways.
    Leaves hang off a curve properly rather than off a straight line nearby. */
function frameAt(p0: Pt, c: Pt, p1: Pt, t: number) {
  const u = 1 - t
  const p = {
    x: u * u * p0.x + 2 * u * t * c.x + t * t * p1.x,
    y: u * u * p0.y + 2 * u * t * c.y + t * t * p1.y,
  }
  const dx = 2 * u * (c.x - p0.x) + 2 * t * (p1.x - c.x)
  const dy = 2 * u * (c.y - p0.y) + 2 * t * (p1.y - c.y)
  const m = Math.hypot(dx, dy) || 1
  const tan = { x: dx / m, y: dy / m }
  const nor = { x: -tan.y, y: tan.x }
  return { p, tan, nor, deg: (Math.atan2(nor.y, nor.x) * 180) / Math.PI }
}

function leaf(key: string, cx: number, cy: number, len: number, deg: number) {
  return (
    <ellipse
      key={key}
      cx={round(cx)}
      cy={round(cy)}
      rx={round(len)}
      ry={round(len * 0.34)}
      transform={`rotate(${round(deg)} ${round(cx)} ${round(cy)})`}
      fill={INK}
      fillOpacity="0.1"
    />
  )
}

const pressed: Family = (rng) => {
  const plant = pick(rng, ['bloom', 'umbel', 'spike', 'frond', 'sprig'] as const)

  // A spike carries its flowers up the top half, so it needs the height; an
  // umbel opens into a wide head and has to stop low enough to fit it.
  const headY =
    plant === 'spike'
      ? between(rng, 18, 24)
      : plant === 'umbel'
        ? between(rng, 46, 54)
        : between(rng, 28, 36)

  // ±20px of bend over ~90px of stem. The earlier ±9 was invisible at any
  // size, which is why every plant came out looking ruled.
  const curve = between(rng, -20, 20)
  const base = { x: MID + between(rng, -5, 5), y: SIZE - 10 }
  const top = { x: MID + curve * 0.4, y: headY }
  const ctrl = { x: MID + curve, y: (base.y + top.y) / 2 }
  const frame = (t: number) => frameAt(base, ctrl, top, t)

  const pairAt = (key: string, t: number, len: number, tilt: number) => {
    const { p, nor, deg } = frame(t)
    return (
      <g key={key}>
        {leaf(`${key}r`, p.x + nor.x * len, p.y + nor.y * len, len, deg + tilt)}
        {leaf(`${key}l`, p.x - nor.x * len, p.y - nor.y * len, len, deg - tilt)}
      </g>
    )
  }

  const parts: ReactNode[] = []

  if (plant === 'bloom') {
    const pairs = intBetween(rng, 3, 4)
    for (let i = 0; i < pairs; i += 1) {
      parts.push(
        pairAt(
          `leaf${i}`,
          0.24 + (i / pairs) * 0.48,
          between(rng, 7, 11),
          between(rng, 24, 42),
        ),
      )
    }
    const petals = intBetween(rng, 5, 8)
    const petalR = between(rng, 8, 11)
    for (let i = 0; i < petals; i += 1) {
      const a = (i / petals) * Math.PI * 2 + rng() * 0.3
      const cx = round(top.x + Math.cos(a) * petalR * 0.62)
      const cy = round(top.y + Math.sin(a) * petalR * 0.62)
      parts.push(
        <ellipse
          key={`petal${i}`}
          cx={cx}
          cy={cy}
          rx={round(petalR * 0.62)}
          ry={round(petalR * 0.3)}
          transform={`rotate(${round((a * 180) / Math.PI)} ${cx} ${cy})`}
          fill={INK}
          fillOpacity="0.14"
        />,
      )
    }
    parts.push(
      <circle
        key="eye"
        cx={round(top.x)}
        cy={round(top.y)}
        r={round(petalR * 0.24)}
        fill={INK}
        fillOpacity="0.5"
        stroke="none"
      />,
    )
  }

  if (plant === 'umbel') {
    const rays = intBetween(rng, 5, 8)
    const reach = between(rng, 20, 27)
    for (let i = 0; i < rays; i += 1) {
      const a = -Math.PI / 2 + (i / (rays - 1) - 0.5) * 1.7
      // Flatter than it is wide: an umbel spreads sideways more than it rises.
      const ex = round(top.x + Math.cos(a) * reach)
      const ey = round(top.y + Math.sin(a) * reach * 0.85)
      parts.push(
        <path
          key={`ray${i}`}
          d={`M ${round(top.x)} ${round(top.y)} L ${ex} ${ey}`}
          strokeWidth="0.7"
        />,
        <circle
          key={`floret${i}`}
          cx={ex}
          cy={ey}
          r={round(between(rng, 1.6, 2.6))}
          fill={INK}
          fillOpacity="0.3"
          stroke="none"
        />,
      )
    }
    parts.push(pairAt('leaf0', 0.3, between(rng, 8, 11), between(rng, 26, 40)))
  }

  if (plant === 'spike') {
    const buds = intBetween(rng, 9, 14)
    for (let i = 0; i < buds; i += 1) {
      const t = 0.5 + (i / buds) * 0.5
      const { p, nor, deg } = frame(t)
      const side = i % 2 === 0 ? 1 : -1
      const taper = 1 - (i / buds) * 0.45 // buds get smaller toward the tip
      const cx = round(p.x + nor.x * side * 2.6 * taper)
      const cy = round(p.y + nor.y * side * 2.6 * taper)
      parts.push(
        <ellipse
          key={`bud${i}`}
          cx={cx}
          cy={cy}
          rx={round(3.4 * taper)}
          ry={round(2.1 * taper)}
          transform={`rotate(${round(deg + side * 30)} ${cx} ${cy})`}
          fill={INK}
          fillOpacity="0.22"
        />,
      )
    }
    parts.push(pairAt('leaf0', 0.16, between(rng, 6, 9), between(rng, 20, 34)))
  }

  if (plant === 'frond') {
    const pinnae = intBetween(rng, 9, 13)
    for (let i = 0; i < pinnae; i += 1) {
      const t = 0.14 + (i / pinnae) * 0.82
      const { p, tan, nor } = frame(t)
      // A frond is genuinely tall and narrow, but at 9–13 it drew a spine with
      // whiskers and left most of the board empty. It has to carry a cover.
      const len = between(rng, 15, 20) * (1 - t * 0.35)
      for (const side of [1, -1]) {
        // Leaning back down the stem rather than straight out, the way a
        // frond's pinnae lie once it has been pressed flat.
        const dx = nor.x * side - tan.x * 0.42
        const dy = nor.y * side - tan.y * 0.42
        const m = Math.hypot(dx, dy) || 1
        parts.push(
          <path
            key={`pinna${i}${side}`}
            d={`M ${round(p.x)} ${round(p.y)} L ${round(p.x + (dx / m) * len)} ${round(p.y + (dy / m) * len)}`}
            strokeWidth="0.8"
          />,
        )
      }
    }
  }

  if (plant === 'sprig') {
    const pairs = intBetween(rng, 2, 3)
    for (let i = 0; i < pairs; i += 1) {
      parts.push(
        pairAt(
          `leaf${i}`,
          0.28 + i * 0.22,
          between(rng, 8, 12),
          between(rng, 28, 46),
        ),
      )
    }
    const berries = intBetween(rng, 3, 4)
    for (let i = 0; i < berries; i += 1) {
      const a = -Math.PI / 2 + (i / (berries - 1) - 0.5) * 1.9
      const stalk = between(rng, 6, 9)
      const bx = round(top.x + Math.cos(a) * stalk)
      const by = round(top.y + Math.sin(a) * stalk)
      parts.push(
        <path
          key={`stalk${i}`}
          d={`M ${round(top.x)} ${round(top.y)} L ${bx} ${by}`}
          strokeWidth="0.7"
        />,
        <circle
          key={`berry${i}`}
          cx={bx}
          cy={by}
          r={round(between(rng, 2.4, 3.4))}
          fill={INK}
          fillOpacity="0.28"
        />,
      )
    }
  }

  return (
    <g strokeWidth="0.9">
      <path
        d={`M ${round(base.x)} ${round(base.y)} Q ${round(ctrl.x)} ${round(ctrl.y)} ${round(top.x)} ${round(top.y)}`}
      />
      {parts}
    </g>
  )
}

/* ---- Block print ----
   Cut shapes, not drawn ones: chunky filled leaves off a heavy stem. The whole
   block is printed twice, the second pass a hair out of register, which is the
   detail that reads as "printed by hand" more than any amount of texture. */
const block: Family = (rng) => {
  const leaves = intBetween(rng, 4, 6)
  const lean = between(rng, -6, 6)

  const plate = (
    <g>
      <path
        d={`M ${MID} ${SIZE - 14} Q ${round(MID + lean)} ${MID} ${round(MID + lean * 0.5)} 26`}
        strokeWidth="2.6"
      />
      {Array.from({ length: leaves }, (_, i) => {
        const t = (i + 0.5) / leaves
        const y = round(SIZE - 16 - t * (SIZE - 46))
        const x = round(MID + lean * (1 - t) * 0.6)
        const side = i % 2 === 0 ? 1 : -1
        const len = round(between(rng, 15, 23))
        const fat = round(between(rng, 6.5, 9.5))
        const rise = round(between(rng, 6, 12))
        // A cut leaf: out along the vein, belly on one side, back on the other.
        return (
          <path
            key={i}
            d={`M ${x} ${y} C ${x + side * len * 0.4} ${y - rise - fat} ${x + side * len * 0.85} ${y - rise - fat * 0.6} ${x + side * len} ${y - rise} C ${x + side * len * 0.7} ${y - rise + fat * 0.5} ${x + side * len * 0.35} ${y + fat * 0.4} ${x} ${y} Z`}
            fill={INK}
            fillOpacity="0.55"
            stroke="none"
          />
        )
      })}
      <circle cx={round(MID + lean * 0.5)} cy="22" r="4.5" fill={INK} fillOpacity="0.55" stroke="none" />
    </g>
  )

  return (
    <>
      <g transform={`translate(${round(between(rng, 0.9, 1.8))} ${round(between(rng, 0.7, 1.6))})`} opacity="0.22">
        {plate}
      </g>
      {plate}
    </>
  )
}

/* ---- Cross-stitch sampler ----
   The motifs are counted out by hand, not generated, because that is how
   samplers actually work: a stitcher picks a device out of a pattern book and
   counts it onto the cloth. A seeded random fill was tried first and it read
   as static — symmetric static, but static. A shape has to be a shape.

   The seed chooses which device and how it is finished; the handmade quality
   comes from the stitches themselves, each one a hair off square, the way a
   hand pulls thread. */
const SAMPLERS = [
  // Pine
  [
    '.....x.....',
    '....xxx....',
    '...xxxxx...',
    '....xxx....',
    '...xxxxx...',
    '..xxxxxxx..',
    '...xxxxx...',
    '..xxxxxxx..',
    '.xxxxxxxxx.',
    '.....x.....',
    '....xxx....',
  ],
  // Bloom
  [
    '..xx...xx..',
    '.xxxx.xxxx.',
    'xxxxxxxxxxx',
    'xxxxxxxxxxx',
    '.xxxxxxxxx.',
    '..xxxxxxx..',
    '...xxxxx...',
    '....xxx....',
    '.....x.....',
    '....x.x....',
    '...x...x...',
  ],
  // Compass
  [
    '.....x.....',
    '....xxx....',
    '.x..xxx..x.',
    '..x.xxx.x..',
    '...xxxxx...',
    'xxxxxxxxxxx',
    '...xxxxx...',
    '..x.xxx.x..',
    '.x..xxx..x.',
    '....xxx....',
    '.....x.....',
  ],
  // Rose medallion
  [
    '...xxxxx...',
    '..x.....x..',
    '.x..xxx..x.',
    '.x.x...x.x.',
    '.x.x.x.x.x.',
    '.x.x...x.x.',
    '.x..xxx..x.',
    '..x.....x..',
    '...xxxxx...',
    '.....x.....',
    '....xxx....',
  ],
] as const

const stitch: Family = (rng) => {
  const motif = pick(rng, SAMPLERS)
  const corners = rng() < 0.55
  const cell = 8.6
  const originX = MID - ((motif[0].length - 1) / 2) * cell
  const originY = MID - ((motif.length - 1) / 2) * cell
  const marks: ReactNode[] = []

  const cross = (key: string, x: number, y: number, s: number) => {
    // No two stitches sit at exactly the same angle in real needlework.
    const t = round(between(rng, -6, 6))
    return (
      <path
        key={key}
        transform={`rotate(${t} ${x} ${y})`}
        d={`M ${round(x - s)} ${round(y - s)} L ${round(x + s)} ${round(y + s)} M ${round(x + s)} ${round(y - s)} L ${round(x - s)} ${round(y + s)}`}
      />
    )
  }

  motif.forEach((row, r) => {
    for (let c = 0; c < row.length; c += 1) {
      if (row[c] !== 'x') continue
      marks.push(
        cross(
          `${r}-${c}`,
          round(originX + c * cell),
          round(originY + r * cell),
          round(cell * 0.32),
        ),
      )
    }
  })

  if (corners) {
    const reach = ((motif[0].length - 1) / 2) * cell + cell * 1.6
    for (const [sx, sy] of [
      [-1, -1],
      [1, -1],
      [-1, 1],
      [1, 1],
    ]) {
      marks.push(
        cross(`corner-${sx}-${sy}`, round(MID + sx * reach), round(MID + sy * reach), 2.8),
      )
    }
  }

  return <g strokeWidth="1.5">{marks}</g>
}

/* ---- Folk repeat ----
   Banded rows of one repeating glyph, ruled off from each other the way a
   printed endpaper or a woven border is. Each band gets its own glyph and its
   own count, so the three bands rhyme without matching. */
const folk: Family = (rng) => {
  const glyphs = ['tulip', 'diamond', 'sprout', 'chevron'] as const
  const bands = 3
  const gap = 30

  return (
    <g strokeWidth="1.2">
      {Array.from({ length: bands }, (_, b) => {
        const y = round(MID - gap + b * gap)
        const glyph = pick(rng, glyphs)
        const count = intBetween(rng, 3, 5)
        const span = 92
        const step = span / count
        const startX = MID - span / 2 + step / 2

        return (
          <g key={b}>
            {b > 0 && (
              <path
                d={`M ${round(MID - 40)} ${round(y - gap / 2)} L ${round(MID + 40)} ${round(y - gap / 2)}`}
                strokeWidth="0.7"
                opacity="0.45"
              />
            )}
            {Array.from({ length: count }, (_, i) => (
              <g key={i} transform={`translate(${round(startX + i * step)} ${y})`}>
                {folkGlyph(glyph, round(between(rng, 7.5, 10)))}
              </g>
            ))}
          </g>
        )
      })}
    </g>
  )
}

function folkGlyph(kind: 'tulip' | 'diamond' | 'sprout' | 'chevron', s: number) {
  switch (kind) {
    case 'tulip':
      return (
        <>
          <path d={`M ${-s * 0.6} ${-s * 0.1} L ${-s * 0.6} ${-s * 0.7} M 0 ${-s * 0.25} L 0 ${-s * 0.95} M ${s * 0.6} ${-s * 0.1} L ${s * 0.6} ${-s * 0.7}`} />
          <path d={`M ${-s * 0.6} ${-s * 0.1} Q 0 ${s * 0.55} ${s * 0.6} ${-s * 0.1}`} fill={INK} fillOpacity="0.35" />
          <path d={`M 0 ${s * 0.35} L 0 ${s * 0.95}`} />
        </>
      )
    case 'diamond':
      return (
        <>
          <path d={`M 0 ${-s} L ${s * 0.7} 0 L 0 ${s} L ${-s * 0.7} 0 Z`} fill={INK} fillOpacity="0.3" />
          <path d={`M 0 ${-s * 0.45} L ${s * 0.32} 0 L 0 ${s * 0.45} L ${-s * 0.32} 0 Z`} />
        </>
      )
    case 'sprout':
      return (
        <>
          <path d={`M 0 ${s} L 0 ${-s * 0.5}`} />
          <path d={`M 0 ${s * 0.1} Q ${-s * 0.8} ${-s * 0.2} ${-s * 0.5} ${-s * 0.85}`} />
          <path d={`M 0 ${-s * 0.1} Q ${s * 0.8} ${-s * 0.4} ${s * 0.5} ${-s} `} />
        </>
      )
    case 'chevron':
      return (
        <>
          <path d={`M ${-s * 0.8} ${s * 0.35} L 0 ${-s * 0.5} L ${s * 0.8} ${s * 0.35}`} />
          <path d={`M ${-s * 0.8} ${s * 0.85} L 0 0 L ${s * 0.8} ${s * 0.85}`} opacity="0.5" />
        </>
      )
  }
}

/* ---- Stamped cloth ----
   The blind-stamped device on a cloth binding: a ruled ring, a border of short
   radial marks struck from a single tool, and a small centre device. This is
   the most formal of the five, and the one that suits a book with a long or
   plain title, where a botanical would crowd the type. */
const cloth: Family = (rng) => {
  /* Four independent choices rather than one, because a stamp is assembled
     from separate tools: the binder picks a border wheel, a rule, and a centre
     device. A first pass varied only the tick count and the centre, and two
     books drawn ten apart came out looking like the same stamp — which is
     exactly the failure this family has to avoid, since it is the most rigid
     of the five and has the least room to hide a repeat. */
  const outer = between(rng, 38, 46)
  const border = pick(rng, ['dash', 'dot', 'alternating', 'none'] as const)
  const ticks = intBetween(rng, 16, 30)
  const inner = round(outer - between(rng, 8, 15))
  const doubleRule = rng() < 0.45
  const centre = pick(rng, ['diamond', 'star', 'dot', 'cross', 'rosette'] as const)
  const spokes = pick(rng, [4, 6, 8] as const)
  const deviceR = round(between(rng, 10, 15))

  return (
    <g strokeWidth="1.1">
      {border !== 'none' && (
        <circle cx={MID} cy={MID} r={round(outer)} strokeWidth="0.8" opacity="0.5" />
      )}
      <circle cx={MID} cy={MID} r={inner} strokeWidth="1.4" />
      {doubleRule && (
        <circle cx={MID} cy={MID} r={round(inner - 3.2)} strokeWidth="0.7" opacity="0.6" />
      )}

      {border !== 'none' &&
        Array.from({ length: ticks }, (_, i) => {
          const a = (i / ticks) * Math.PI * 2
          const cx = round(MID + Math.cos(a) * (outer - 3.5))
          const cy = round(MID + Math.sin(a) * (outer - 3.5))
          if (border === 'dot') {
            return <circle key={i} cx={cx} cy={cy} r="1.3" fill={INK} stroke="none" />
          }
          const long = border === 'alternating' ? i % 2 === 0 : true
          const r1 = outer - (long ? 6 : 4)
          const r2 = outer - 1.4
          return (
            <path
              key={i}
              d={`M ${round(MID + Math.cos(a) * r1)} ${round(MID + Math.sin(a) * r1)} L ${round(MID + Math.cos(a) * r2)} ${round(MID + Math.sin(a) * r2)}`}
              strokeWidth="1.6"
            />
          )
        })}

      {centre === 'diamond' && (
        <path
          d={`M ${MID} ${round(MID - deviceR)} L ${round(MID + deviceR * 0.7)} ${MID} L ${MID} ${round(MID + deviceR)} L ${round(MID - deviceR * 0.7)} ${MID} Z`}
          fill={INK}
          fillOpacity="0.35"
        />
      )}
      {centre === 'star' &&
        Array.from({ length: spokes }, (_, i) => {
          const a = (i / spokes) * Math.PI * 2
          return (
            <path
              key={i}
              d={`M ${MID} ${MID} L ${round(MID + Math.cos(a) * deviceR)} ${round(MID + Math.sin(a) * deviceR)}`}
              strokeWidth="1.3"
            />
          )
        })}
      {centre === 'dot' && (
        <circle cx={MID} cy={MID} r={round(deviceR * 0.45)} fill={INK} fillOpacity="0.4" stroke="none" />
      )}
      {centre === 'cross' && (
        <path
          d={`M ${MID} ${round(MID - deviceR)} L ${MID} ${round(MID + deviceR)} M ${round(MID - deviceR)} ${MID} L ${round(MID + deviceR)} ${MID}`}
          strokeWidth="1.5"
        />
      )}
      {centre === 'rosette' &&
        Array.from({ length: 6 }, (_, i) => {
          const a = (i / 6) * Math.PI * 2
          return (
            <ellipse
              key={i}
              cx={round(MID + Math.cos(a) * deviceR * 0.45)}
              cy={round(MID + Math.sin(a) * deviceR * 0.45)}
              rx={round(deviceR * 0.42)}
              ry={round(deviceR * 0.24)}
              transform={`rotate(${round((a * 180) / Math.PI)} ${round(MID + Math.cos(a) * deviceR * 0.45)} ${round(MID + Math.sin(a) * deviceR * 0.45)})`}
              fill={INK}
              fillOpacity="0.18"
            />
          )
        })}
    </g>
  )
}

const FAMILIES: Family[] = [pressed, block, stitch, folk, cloth]

export default CoverArt
